##===----------------------------------------------------------------------===//
##
##                         === The HTool Project ===
##
##  This  document  is the property of "Is This On?" It is considered to be
##  confidential and proprietary and may not be, in any form, reproduced or
##  transmitted, in whole or in part, without express permission of Is This
##  On?.
##
##  Copyright (C) 2023, Is This On? Holdings Limited
##
##  Harry Moulton <me@h3adsh0tzz.com>
##
##===----------------------------------------------------------------------===//

TestSuite:
  suite_name: macho-tests
  git:
    remote: "https://github.com/h3adshotzz/htoolv3-testing.git"
    branch: master
  tests:
  -
    # A valid Mach-O
    name: macho-test_valid-macho-file
    flags: "macho -h -l"
    file: "./htoolv3-testing/ps.arm64"
  -
    # A valid FAT file with no --arch flag
    name: macho-test_valid-fat-no-arch
    flags: "macho -h -l"
    file: "./htoolv3-testing/ps.universal"
  -
    # A valid FAT file with --arch flag
    name: macho-test_valid-fat-with-arch
    flags: "macho -h -l --arch=arm64e"
    file: "./htoolv3-testing/ps.universal"
  -
    # An invalid/corrupted Mach-O
    name: macho-test_invalid-macho
    flags: "macho -h -l"
    file: "./htoolv3-testing/invalid.arm64"
  -
    # Nonexistent file
    name: macho-test_no-file
    flags: "macho -h -l"
    file: "macho-basic-1.bin"
