name: htool-linux

on:
  push:
    branches-ignore:
      - "topics/ci-artifact"

jobs:
  Build:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3

    # Checkout and pull libhelper
    - name: libhelper-configure
      run: git submodule init && git submodule update

    # Configure the project.
    - name: htool-configure
      run: cmake -B build/ -D CMAKE_C_COMPILER=clang -DHTOOL_DISABLE_VERSION=1

    # Build
    - name: build
      id: htool-linux-build
      run: |
        cd build/;
        make;
        ls -la;
        echo "HTOOL_SOURCE_VERSION=$(python3 ../config/version_fetch.py -f ../src/MasterVersion)" >> $GITHUB_ENV

    # Upload Artefact
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.HTOOL_SOURCE_VERSION }}-linux-internal
        path: build/

  Test:
    runs-on: "ubuntu-latest"
    needs: "Build"

    steps:
    - name: test
      run: |
        ls -la;
        ls -la build/;