name: htool-macos

on: push

jobs:
  Build:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v3

    # Checkout and pull libhelper
    - name: libhelper-configure
      run: git submodule init && git submodule update

    # Configure the project.
    - name: htool-configure
      run: cmake -B build/ -D CMAKE_C_COMPILER=clang -DHTOOL_DISABLE_VERSION=1

    # Build
    - name: build
      id: htool-macos-build
      run: |
        cd build/;
        make;
        ls -la;
        echo "HTOOL_SOURCE_VERSION=$(python3 ../config/version_fetch.py -f ../src/MasterVersion)" >> $GITHUB_ENV

    # Upload Artefact
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.HTOOL_SOURCE_VERSION }}-macos-internal
        path: build/

  Test:
    runs-on: "self-hosted"
    needs: "Build"

    steps:
    - name: test
      run: |
        ls -la;
        ls -la build/;