name: htool-results-test

on: push

jobs:
  Build:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v3

    - name: Publish Test Results 
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: test.xml

