name: htool-results-test

on: push

jobs:
  Build:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v3

    - name: Publish Test Results 
      uses: dorny/test-reporter@v1
      if: always()
      with:
        path: test.xml
        name: "junit results test"
        reporter: java-junit

