name: htool-results-test

on: push

jobs:
  Build:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v3

    - name: Publish Test Results 
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: test.xml

